# Generated by Django 6.0.2 on 2026-02-06 16:35

import social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=social_media.models.upload_profile_pictures,
            ),
        ),
    ]
