# Generated by Django 6.0.2 on 2026-02-06 19:31

import social_media.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0002_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", social_media.models.UserManager()),
            ],
        ),
    ]
