# Generated by Django 6.0.2 on 2026-02-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0005_post_postmedia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
