# Generated by Django 6.0.2 on 2026-02-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0006_alter_post_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmedia",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="social_media.post",
            ),
        ),
    ]
