# Generated by Django 6.0.2 on 2026-02-13 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0007_alter_postmedia_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postmedia",
            old_name="media",
            new_name="file",
        ),
        migrations.AlterField(
            model_name="postmedia",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="social_media.post",
            ),
        ),
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=50)),
                (
                    "post",
                    models.ManyToManyField(
                        related_name="hashtags", to="social_media.post"
                    ),
                ),
            ],
        ),
    ]
