# Generated by Django 6.0.2 on 2026-02-13 17:30

import social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "social_media",
            "0008_rename_media_postmedia_file_alter_postmedia_post_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmedia",
            name="file",
            field=models.ImageField(upload_to=social_media.models.upload_post_media),
        ),
    ]
