# Generated by Django 6.0.2 on 2026-02-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0009_alter_postmedia_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="text",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
