# Generated by Django 6.0.2 on 2026-02-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0010_alter_hashtag_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hashtag",
            name="post",
        ),
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="social_media.hashtag"
            ),
        ),
    ]
