# Generated by Django 6.0.2 on 2026-02-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0016_comment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("SCH", "Scheduled"), ("PUB", "Published")],
                default="PUB",
                max_length=3,
            ),
        ),
    ]
