# Generated by Django 6.0.2 on 2026-03-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0017_post_published_at_post_scheduled_for_post_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["id"]},
        ),
    ]
